name: example
description: A new Flutter project.
version: 1.0.1+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  panorama: 
    path: ../
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/

publish_to: none
